# 🧪 SkilledUp Life – Regression Testing Workflow
# This workflow runs regression tests (subset of critical tests)
# Currently runs on pull_request only (non-blocking)
# Future: Will run on main branch merges to validate stability
# Note: Regression tests are the same test types (unit/E2E) but focused on critical paths

name: Regression Check

on:
  pull_request:
    branches: [ main, develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  regression-tests:
    name: Critical Path Regression Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run critical unit tests (regression subset)
      run: npm run test:regression:unit
      # This runs a subset of unit tests focused on critical business logic
      
    - name: Run critical E2E tests (regression subset)
      run: npm run test:regression:e2e
      # This runs a subset of E2E tests focused on critical user journeys
      
    - name: Report regression status
      run: |
        echo "✅ Regression tests completed"
        echo "📊 These tests validate critical paths haven't been broken"
        echo "🔗 Future: This will run on main branch merges for stability validation"
        echo "💡 Regression tests = subset of existing tests (unit/E2E) focused on critical functionality" 