# CI Pipeline for Frontend (Linting, Unit, and E2E tests)
# Repository: https://github.com/skilleduplife/frontend
# This is the 'View' in the MVC architecture, communicating with the backend via API.
# Place this file at .github/workflows/ci-frontend.yml (https://github.com/skilleduplife/frontend/tree/main/.github/workflows/ci-frontend.yml) in the frontend repo.
# This workflow runs on pull requests to dev and main branches.

name: CI Pipeline - Frontend

on:
  pull_request:
    branches: [dev, main]

jobs:
  lint:
    name: Lint (Frontend)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Fetch code

      - uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use Node.js 18 for frontend builds

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run ESLint
        run: |
          cd frontend
          npm run lint  # Lint codebase for style and errors

  unit:
    name: Unit Tests (Frontend)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Placeholder for unit tests
        run: echo "Unit tests not yet added"
        # TODO: Replace with: cd frontend && npm run test:unit
        # Add your frontend unit test command above

  e2e:
    name: E2E Tests (Frontend)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Placeholder for E2E tests
        run: echo "E2E tests not yet added"
        # TODO: Replace with: cd frontend && npx playwright test
        # Add your E2E test command above